### PR TITLE
clear the webpack warning

### PR DESCRIPTION
**Pull request by zhaozhiming**
Hi, 
I use moment-jdateformatparse with webpack but have some warning like #11 , and I use vovateleport's answer can clear the warning. So I pull the request to you, please review. 

Thank.

### CODE REVIEW

**Comment by zhaozhiming** [comment]
some test fail, close first, sorry.

**Comment by zhaozhiming** [comment]
It's ok now. Please review to code. Thank you. @MadMG

**Comment by amannn** [comment]
Would be really helpful if this gets merged.

**Comment by amannn** [comment]
@MadMG @herom Is it ok to merge this?

**Comment by herom** [comment]
I'm sorry - I completely lost focus of this PR... for me this looks good to merge 👍 

what about you @MadMG ?

**Comment by amannn** [comment]
@herom Thanks a lot for merging! Would it be possible to get this released in the near future?

**Comment by herom** [comment]
ah, yes - sorry! I thought that @MadMG would release it, but I'll take a look at it and have it released soon (hopefully today) 👍

**Comment by amannn** [comment]
No worries – thanks a lot for your help!

**Comment by amannn** [comment]
@herom Sorry to bother you again, but is it possible that the package isn't released to npm yet? The [moment-jdateformatparser page](https://www.npmjs.com/package/moment-jdateformatparser) there says that version 1.0.2 is the latest release and I'm also not able to install the new 1.1.0 version in a project. Maybe running `npm publish` in the repository is necessary?

Thanks for your help!

**Comment by herom** [comment]
@amannn ya, that's because I wasn't within the list of "collaborators" in npm and I couldn't publish it. I talked to @MadMG the other day and I'm now officially a "collaborator" 😸 so I'm able to release it once I'm at home as we're using a private npm-registry here at work.

sorry for the delay, but at the end of the day it should be released and published 💯

**Comment by amannn** [comment]
@herom Ahh, I see 🙂. Thank you so much!

**Comment by herom** [comment]
You're welcome 👍 

Oh, danke - beste Gruesse aus der Steiermark retour 😉

**Comment by herom** [comment]
@amannn new version released 🥇

**Pull request merged**
