### PR TITLE
adds ability to translate formats that contain escape characters

### PR DESCRIPTION
**Pull request by arikimolloy**
https://github.com/MadMG/moment-jdateformatparser/issues/7#issuecomment-252155592

### CODE REVIEW

**Comment by arikimolloy** [comment]
Doesn't work for escaping single quotes themselves. 

E.g. "hh 'o''clock' a, zzzz" is supposed to display as "12 o'clock PM, Pacific Daylight Time"

but escaping the single quote in o'clock fails.

However, this fix will work on escaping other characters e.g. "ddHHmm'Z'MMMyyyy" will display as "062000ZMay2036"

Tests should also be added.

**Comment by herom** [comment]
Thanks a lot for your contribution @arikimolloy but could you please revert all other changes which are not related to the added functionality itself? This type of PR makes it really cumbersome and in later stages nearly impossible to tell what was really added, as you basically re-arranged the whole file. 😄

**Comment by arikimolloy** [comment]
My bad I think it was my formatter. Now it should only show the actually changed code.

**Comment by herom** [comment]
Awesome - thanks a ton @arikimolloy 👍 

LGTM - what about you @MadMG, are you ok with that?

**Comment by MadMG** [comment]
@herom  sorry for the late repsonse.... 👍

**Pull request merged**
