### PR TITLE
fix day-of-week format mapping

### PR DESCRIPTION
**Pull request by gboros**
better day-of-week format mapping

### CODE REVIEW

**Comment by MadMG** [comment]
Why would this be better? The oracle java documentation says: 

> For formatting, if the number of pattern letters is 4 or more, the full form is used; otherwise a short or abbreviated form is used if available. For parsing, both forms are accepted, independent of the number of pattern letters.

If more than four `E`s are present, a dynamic mapping would make more sense.

**Comment by gboros** [comment]
it is better because now it works also for 'EE' (this was a bug), and also for more then four (but only 5 and 6) - here of course a dynamic mapping would make it complete, not just better

**Comment by MadMG** [comment]
I see, you're right! Thx for the fix for `EE`.

Maybe I have time to add a dynamic mapping in the future.

**Comment by herom** [comment]
:+1:

**Pull request merged**
